DEFAULT_PII_TYPES = [
    "TIME", "USERNAME", "IDCARD", "SOCIALNUMBER", "EMAIL", "PASSPORT",
    "DRIVERLICENSE", "DOB", "LASTNAME1", "IP", "GIVENNAME1", "SEX",
    "TEL", "CITY", "POSTCODE", "STREET", "STATE", "BUILDING", "TITLE",
    "COUNTRY", "DATE", "PASS", "SECADDRESS", "LASTNAME2", "GIVENNAME2",
    "GEOCOORD", "LASTNAME3"
] 